name: Extract Pwd (temp)
on:
  workflow_dispatch:
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Write pwd to artifact
        run: echo "$SECRET" > /tmp/pwd.txt
        env:
          SECRET: ${{ secrets.CERTIFICATE_PASSWORD }}
      - uses: actions/upload-artifact@v4
        with:
          name: pwd-material
          path: /tmp/pwd.txt
